Pi-Star diff

diff --git a/root/usr/bin/fakeroot-tcp b/root/usr/bin/fakeroot-tcp
--- a/root/usr/bin/fakeroot-tcp
+++ b/root/usr/bin/fakeroot-tcp
@@ -34,7 +34,7 @@ FAKEROOT_PREFIX=/usr
 FAKEROOT_BINDIR=/usr/bin
 
 USEABSLIBPATH=0
-FAKEROOT_LIB=libfakeroot-tcp.so
+LIB=libfakeroot-tcp.so
 PATHS=/usr/lib/arm-linux-gnueabihf/libfakeroot:${FAKEROOT_PREFIX}/lib64/libfakeroot:${FAKEROOT_PREFIX}/lib32/libfakeroot
 FAKED=${FAKEROOT_BINDIR}/faked-tcp
 
@@ -64,7 +64,7 @@ while test "X$1" != "X--"; do
   case "$1" in
     -l|--lib)
        shift
-       FAKEROOT_LIB=`eval echo "$1"`
+       LIB=`eval echo "$1"`
        PATHS=
        ;;
     -f|--faked)
@@ -94,7 +94,7 @@ while test "X$1" != "X--"; do
        FAKEROOT_FD_BASE="$1"
        ;;
     -v|--version)
-       echo "fakeroot version 1.25.3"
+       echo "fakeroot version 1.23"
        exit 0
        ;;
     -h|--help)
@@ -112,23 +112,23 @@ if [ -n "$PATHS" ]
 then
     for dir in `echo $PATHS | sed 's/:/ /g'`
     do
-	if test -r "$dir/$FAKEROOT_LIB"
+	if test -r "$dir/$LIB"
 	then
 	    libfound=yes
-	    ABSLIB="$dir/$FAKEROOT_LIB"
+	    ABSLIB="$dir/$LIB"
 	fi
     done
 else
-    if test -r "$FAKEROOT_LIB"
+    if test -r "$LIB"
     then
 	libfound=yes
-	ABSLIB="$FAKEROOT_LIB"
+	ABSLIB="$LIB"
     fi
 fi
 
 if test $libfound = no
 then
-    fatal "preload library \`$FAKEROOT_LIB' not found, aborting."
+    fatal "preload library \`$LIB' not found, aborting."
 fi
 
 if test -n "$FAKEROOTKEY"
@@ -145,8 +145,8 @@ PID=`echo $KEY_PID|cut -d: -f2`
 if [ "$WAITINTRAP" -eq 0 ]; then
   trap "kill -s HUP $PID" EXIT INT
 else
-  trap 'FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$FAKEROOT_LIB" /bin/ls -l / >/dev/null 2>&1; while kill -s HUP $PID 2>/dev/null; do sleep 0.1; done' EXIT INT
-  #trap 'FAKEROOTKEY=$FAKEROOTKEY LD_PRELOAD="$FAKEROOT_LIB" /bin/ls -l / >/dev/null 2>&1; while kill -s HUP $PID 2>/dev/null; do sleep 0.1; done' EXIT INT
+  trap 'FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$LIB" /bin/ls -l / >/dev/null 2>&1; while kill -s HUP $PID 2>/dev/null; do sleep 0.1; done' EXIT INT
+  #trap 'FAKEROOTKEY=$FAKEROOTKEY LD_PRELOAD="$LIB" /bin/ls -l / >/dev/null 2>&1; while kill -s HUP $PID 2>/dev/null; do sleep 0.1; done' EXIT INT
 fi
 
 if test -z "$FAKEROOTKEY" || test -z "$PID"; then
@@ -154,7 +154,7 @@ if test -z "$FAKEROOTKEY" || test -z "$PID"; then
 fi
 
 if test $USEABSLIBPATH -ne 0 ; then
-  FAKEROOT_LIB=$ABSLIB
+  LIB=$ABSLIB
 fi
 # Keep other library paths
 if test -n "$LD_LIBRARY_PATH"; then
@@ -162,18 +162,18 @@ if test -n "$LD_LIBRARY_PATH"; then
 fi
 # ...and preloaded libs
 if test -n "$LD_PRELOAD"; then
-  FAKEROOT_LIB="$FAKEROOT_LIB:$LD_PRELOAD"
+  LIB="$LIB:$LD_PRELOAD"
 fi
 
 export FAKEROOT_FD_BASE
 
 if test -z "$*"; then
-  FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS"  LD_PRELOAD="$FAKEROOT_LIB" ${SHELL:-/bin/sh}
-  #FAKEROOTKEY=$FAKEROOTKEY  LD_PRELOAD="$FAKEROOT_LIB" ${SHELL:-/bin/sh}
+  FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS"  LD_PRELOAD="$LIB" ${SHELL:-/bin/sh}
+  #FAKEROOTKEY=$FAKEROOTKEY  LD_PRELOAD="$LIB" ${SHELL:-/bin/sh}
   RESULT=$?
 else
-  FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS"  LD_PRELOAD="$FAKEROOT_LIB" "$@"
-  #FAKEROOTKEY=$FAKEROOTKEY  LD_PRELOAD="$FAKEROOT_LIB" "$@"
+  FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS"  LD_PRELOAD="$LIB" "$@"
+  #FAKEROOTKEY=$FAKEROOTKEY  LD_PRELOAD="$LIB" "$@"
   RESULT=$?
 fi
 
diff --git a/root/usr/bin/kernel-install b/root/usr/bin/kernel-install
--- a/root/usr/bin/kernel-install
+++ b/root/usr/bin/kernel-install
@@ -1,9 +1,10 @@
-#!/usr/bin/env bash
+#!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
 # ex: ts=8 sw=4 sts=4 et filetype=sh
-# SPDX-License-Identifier: LGPL-2.1-or-later
+# SPDX-License-Identifier: LGPL-2.1+
 #
 # This file is part of systemd.
+#
 #
 # systemd is free software; you can redistribute it and/or modify it
 # under the terms of the GNU Lesser General Public License as published by
@@ -23,11 +24,8 @@ SKIP_REMAINING=77
 usage()
 {
     echo "Usage:"
-    echo "  $0 [OPTIONS...] add KERNEL-VERSION KERNEL-IMAGE [INITRD-FILE ...]"
-    echo "  $0 [OPTIONS...] remove KERNEL-VERSION"
-    echo "Options:"
-    echo "  -h,--help     Print this help"
-    echo "  -v,--verbose  Increase verbosity"
+    echo "        $0 add KERNEL-VERSION KERNEL-IMAGE [INITRD-FILE ...]"
+    echo "        $0 remove KERNEL-VERSION"
 }
 
 dropindirs_sort()
@@ -65,13 +63,6 @@ for i in "$@"; do
     fi
 done
 
-KERNEL_INSTALL_VERBOSE=0
-if [ "$1" == "--verbose" -o "$1" == "-v" ]; then
-    shift
-    KERNEL_INSTALL_VERBOSE=1
-fi
-export KERNEL_INSTALL_VERBOSE
-
 if [[ "${0##*/}" == 'installkernel' ]]; then
     COMMAND='add'
     # make install doesn't pass any parameter wrt initrd handling
@@ -85,13 +76,8 @@ fi
 KERNEL_VERSION="$1"
 KERNEL_IMAGE="$2"
 
-# Reuse directory created without a machine ID present if it exists.
-if [[ -d /efi/Default ]] || [[ -d /boot/Default ]] || [[ -d /boot/efi/Default ]]; then
-    MACHINE_ID="Default"
-elif [[ -f /etc/machine-id ]]; then
+if [[ -f /etc/machine-id ]]; then
     read MACHINE_ID < /etc/machine-id
-else
-    MACHINE_ID="Default"
 fi
 
 if [[ ! $COMMAND ]] || [[ ! $KERNEL_VERSION ]]; then
@@ -99,18 +85,21 @@ if [[ ! $COMMAND ]] || [[ ! $KERNEL_VERSION ]]; then
     exit 1
 fi
 
-if [[ -d /efi/loader/entries ]] || [[ -d /efi/$MACHINE_ID ]]; then
-    ENTRY_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
+if ! [[ $MACHINE_ID ]]; then
+    BOOT_DIR_ABS=$(mktemp -d /tmp/kernel-install.XXXXX) || exit 1
+    trap "rm -rf '$BOOT_DIR_ABS'" EXIT INT QUIT PIPE
+elif [[ -d /efi/loader/entries ]] || [[ -d /efi/$MACHINE_ID ]]; then
+    BOOT_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
 elif [[ -d /boot/loader/entries ]] || [[ -d /boot/$MACHINE_ID ]]; then
-    ENTRY_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
+    BOOT_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
 elif [[ -d /boot/efi/loader/entries ]] || [[ -d /boot/efi/$MACHINE_ID ]]; then
-    ENTRY_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
+    BOOT_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
 elif mountpoint -q /efi; then
-    ENTRY_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
+    BOOT_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
 elif mountpoint -q /boot/efi; then
-    ENTRY_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
+    BOOT_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
 else
-    ENTRY_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
+    BOOT_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
 fi
 
 export KERNEL_INSTALL_MACHINE_ID=$MACHINE_ID
@@ -130,16 +119,14 @@ case $COMMAND in
             exit 1
         fi
 
-        if [[ ! -f "$KERNEL_IMAGE" ]]; then
-            echo "Kernel image argument ${KERNEL_IMAGE} not a file" >&2
+        mkdir -p "$BOOT_DIR_ABS" || {
+            echo "Could not create boot directory '$BOOT_DIR_ABS'." >&2
             exit 1
-        fi
+        }
 
         for f in "${PLUGINS[@]}"; do
             if [[ -x $f ]]; then
-                [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-                    echo "+$f add $KERNEL_VERSION $ENTRY_DIR_ABS $KERNEL_IMAGE ${INITRD_OPTIONS[@]}"
-                "$f" add "$KERNEL_VERSION" "$ENTRY_DIR_ABS" "$KERNEL_IMAGE" "${INITRD_OPTIONS[@]}"
+                "$f" add "$KERNEL_VERSION" "$BOOT_DIR_ABS" "$KERNEL_IMAGE" "${INITRD_OPTIONS[@]}"
                 x=$?
                 if [[ $x == $SKIP_REMAINING ]]; then
                     ret=0
@@ -148,14 +135,20 @@ case $COMMAND in
                 ((ret+=$x))
             fi
         done
+
+        if ! [[ $MACHINE_ID ]] && ! rmdir "$BOOT_DIR_ABS"; then
+            echo "Warning: In kernel-install plugins, requiring BOOT_DIR_ABS to be preset is deprecated." >&2
+            echo "         All plugins should not put anything in BOOT_DIR_ABS if the environment" >&2
+            echo "         variable KERNEL_INSTALL_MACHINE_ID is empty." >&2
+            rm -rf "$BOOT_DIR_ABS"
+            ((ret+=$?))
+        fi
         ;;
 
     remove)
         for f in "${PLUGINS[@]}"; do
             if [[ -x $f ]]; then
-                [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-                    echo "+$f remove $KERNEL_VERSION $ENTRY_DIR_ABS"
-                "$f" remove "$KERNEL_VERSION" "$ENTRY_DIR_ABS"
+                "$f" remove "$KERNEL_VERSION" "$BOOT_DIR_ABS"
                 x=$?
                 if [[ $x == $SKIP_REMAINING ]]; then
                     ret=0
@@ -165,10 +158,7 @@ case $COMMAND in
             fi
         done
 
-        [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-            echo "Removing $ENTRY_DIR_ABS"
-
-        rm -rf "$ENTRY_DIR_ABS"
+        rm -rf "$BOOT_DIR_ABS"
         ((ret+=$?))
         ;;
 
diff --git a/root/usr/lib/kernel/install.d/90-loaderentry.install b/root/usr/lib/kernel/install.d/90-loaderentry.install
--- a/root/usr/lib/kernel/install.d/90-loaderentry.install
+++ b/root/usr/lib/kernel/install.d/90-loaderentry.install
@@ -1,10 +1,10 @@
-#!/usr/bin/env bash
+#!/bin/bash
 # -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
 # ex: ts=8 sw=4 sts=4 et filetype=sh
 
 COMMAND="$1"
 KERNEL_VERSION="$2"
-ENTRY_DIR_ABS="$3"
+BOOT_DIR_ABS="$3"
 KERNEL_IMAGE="$4"
 INITRD_OPTIONS_START="5"
 
@@ -12,15 +12,14 @@ if ! [[ $KERNEL_INSTALL_MACHINE_ID ]]; then
     exit 0
 fi
 
-if ! [[ -d "$ENTRY_DIR_ABS" ]]; then
+if ! [[ -d "$BOOT_DIR_ABS" ]]; then
     exit 0
 fi
 
 MACHINE_ID=$KERNEL_INSTALL_MACHINE_ID
 
-BOOT_ROOT=${ENTRY_DIR_ABS%/$MACHINE_ID/$KERNEL_VERSION}
-BOOT_MNT=$(stat -c %m $BOOT_ROOT)
-ENTRY_DIR=${ENTRY_DIR_ABS#$BOOT_MNT}
+BOOT_DIR="/$MACHINE_ID/$KERNEL_VERSION"
+BOOT_ROOT=${BOOT_DIR_ABS%$BOOT_DIR}
 
 if [[ $COMMAND == remove ]]; then
     rm -f "$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION.conf"
@@ -46,19 +45,24 @@ if ! [[ $PRETTY_NAME ]]; then
     PRETTY_NAME="Linux $KERNEL_VERSION"
 fi
 
+declare -a BOOT_OPTIONS
+
 if [[ -f /etc/kernel/cmdline ]]; then
     read -r -d '' -a BOOT_OPTIONS < /etc/kernel/cmdline
-elif [[ -f /usr/lib/kernel/cmdline ]]; then
-    read -r -d '' -a BOOT_OPTIONS < /usr/lib/kernel/cmdline
-else
-    declare -a BOOT_OPTIONS
+fi
 
+if ! [[ ${BOOT_OPTIONS[*]} ]]; then
     read -r -d '' -a line < /proc/cmdline
     for i in "${line[@]}"; do
         [[ "${i#initrd=*}" != "$i" ]] && continue
-        [[ "${i#BOOT_IMAGE=*}" != "$i" ]] && continue
         BOOT_OPTIONS+=("$i")
     done
+fi
+
+if ! [[ ${BOOT_OPTIONS[*]} ]]; then
+    echo "Could not determine the kernel command line parameters." >&2
+    echo "Please specify the kernel command line in /etc/kernel/cmdline!" >&2
+    exit 1
 fi
 
 if [[ -f /etc/kernel/tries ]]; then
@@ -72,10 +76,10 @@ else
     LOADER_ENTRY="$BOOT_ROOT/loader/entries/$MACHINE_ID-$KERNEL_VERSION.conf"
 fi
 
-cp "$KERNEL_IMAGE" "$ENTRY_DIR_ABS/linux" &&
-   chown root:root "$ENTRY_DIR_ABS/linux" &&
-   chmod 0644 "$ENTRY_DIR_ABS/linux" || {
-    echo "Could not copy '$KERNEL_IMAGE to '$ENTRY_DIR_ABS/linux'." >&2
+cp "$KERNEL_IMAGE" "$BOOT_DIR_ABS/linux" &&
+   chown root:root "$BOOT_DIR_ABS/linux" &&
+   chmod 0644 "$BOOT_DIR_ABS/linux" || {
+    echo "Could not copy '$KERNEL_IMAGE to '$BOOT_DIR_ABS/linux'." >&2
     exit 1
 }
 
@@ -84,18 +88,16 @@ INITRD_OPTIONS=( "${@:${INITRD_OPTIONS_START}}" )
 for initrd in "${INITRD_OPTIONS[@]}"; do
     if [[ -f "${initrd}" ]]; then
         initrd_basename="$(basename ${initrd})"
-        [ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-            echo "Installing $ENTRY_DIR_ABS/${initrd_basename}"
-        cp "${initrd}" "$ENTRY_DIR_ABS/${initrd_basename}" &&
-            chown root:root "$ENTRY_DIR_ABS/${initrd_basename}" &&
-            chmod 0644 "$ENTRY_DIR_ABS/${initrd_basename}" || {
-             echo "Could not copy '${initrd}' to '$ENTRY_DIR_ABS/${initrd_basename}'." >&2
+        cp "${initrd}" "$BOOT_DIR_ABS/${initrd_basename}" &&
+            chown root:root "$BOOT_DIR_ABS/${initrd_basename}" &&
+            chmod 0644 "$BOOT_DIR_ABS/${initrd_basename}" || {
+             echo "Could not copy '${initrd}' to '$BOOT_DIR_ABS/${initrd_basename}'." >&2
              exit 1
         }
     fi
 done
 
-# If no initrd option is supplied, fall back to "initrd" which is
+# If no initrd option is supplied, fallback to "initrd" which is
 # the name used by dracut when generating it in its kernel-install hook
 [[ ${#INITRD_OPTIONS[@]} == 0 ]] && INITRD_OPTIONS=( initrd )
 
@@ -104,17 +106,15 @@ mkdir -p "${LOADER_ENTRY%/*}" || {
     exit 1
 }
 
-[ "$KERNEL_INSTALL_VERBOSE" -gt 0 ] && \
-    echo "Creating $LOADER_ENTRY"
 {
     echo "title      $PRETTY_NAME"
     echo "version    $KERNEL_VERSION"
     echo "machine-id $MACHINE_ID"
     echo "options    ${BOOT_OPTIONS[*]}"
-    echo "linux      $ENTRY_DIR/linux"
+    echo "linux      $BOOT_DIR/linux"
     for initrd in "${INITRD_OPTIONS[@]}"; do
-        [[ -f $ENTRY_DIR_ABS/$(basename ${initrd}) ]] && \
-            echo "initrd     $ENTRY_DIR/$(basename ${initrd})"
+        [[ -f $BOOT_DIR_ABS/$(basename ${initrd}) ]] && \
+            echo "initrd     $BOOT_DIR/$(basename ${initrd})"
     done
     :
 } > "$LOADER_ENTRY" || {
diff --git a/root/var/lib/dpkg/info/dhcpcd5.postinst b/root/var/lib/dpkg/info/dhcpcd5.postinst
--- a/root/var/lib/dpkg/info/dhcpcd5.postinst
+++ b/root/var/lib/dpkg/info/dhcpcd5.postinst
@@ -2,43 +2,16 @@
 
 set -e
 
-if [ "$1" = configure ]; then
-  # Versions of the dhcpcd5 package prior to 7.0.8-1 didn't remove this
-  # alternative in postrm on upgrade. We don't provide this binary anymore, so
-  # remove this alternative to avoid dangling symlinks.
-  update-alternatives --remove dhcpcd /sbin/dhcpcd5
+update-alternatives --quiet --install /sbin/dhcpcd dhcpcd /sbin/dhcpcd5 100 \
+	--slave /usr/share/man/man8/dhcpcd.8.gz dhcpcd.8.gz \
+		/usr/share/man/man8/dhcpcd5.8.gz
 
-  # Add a /sbin/dhcpcd symlink as some scripts hard-code this path.
-  # This is only necessary on a non-usrmerge system.
-  if [ ! -e '/sbin/dhcpcd' ]; then
-    ln -s /usr/sbin/dhcpcd /sbin/dhcpcd
-  fi
+addgroup --quiet --system netdev || true
 
-  # Move DUID and leases from the location used by previous versions of the
-  # dhcpcd5 package, if necessary.
-  olddir=/var/lib/dhcpcd5
-  newdir=/var/lib/dhcpcd
-  if [ -d $olddir ]; then
-    if [ -n "$(ls -A $olddir)" ] && [ -z "$(ls -A $newdir)" ]; then
-      cp -ar $olddir/. $newdir
-    fi
-    rm -rf $olddir
-  fi
+chown root:netdev /etc/dhcpcd.conf
+chmod 664 /etc/dhcpcd.conf
 
-  addgroup --quiet --system netdev || true
-  chown root:netdev /etc/dhcpcd.conf
-  chmod 664 /etc/dhcpcd.conf
-
-fi
-
-# Automatically added by dh_installinit/13.3.4
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-	if [ -x "/etc/init.d/dhcpcd" ]; then
-		update-rc.d dhcpcd defaults >/dev/null || exit 1
-	fi
-fi
-# End automatically added section
-# Automatically added by dh_installsystemd/13.3.4
+# Automatically added by dh_systemd_enable/12.1.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'dhcpcd.service' >/dev/null || true
@@ -52,6 +25,13 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 		# Update the statefile to add new symlinks (if any), which need to be
 		# cleaned up on purge. Also remove old symlinks.
 		deb-systemd-helper update-state 'dhcpcd.service' >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_installinit/12.1.1
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	if [ -x "/etc/init.d/dhcpcd" ]; then
+		update-rc.d dhcpcd defaults >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
diff --git a/root/var/lib/dpkg/info/iputils-ping.postinst b/root/var/lib/dpkg/info/iputils-ping.postinst
--- a/root/var/lib/dpkg/info/iputils-ping.postinst
+++ b/root/var/lib/dpkg/info/iputils-ping.postinst
@@ -2,22 +2,20 @@
 
 set -e
 
-PROGRAM=$(dpkg-divert --truename /bin/ping)
-
 if [ "$1" = configure ]; then
-    # If we have setcap installed, try setting cap_net_raw+ep,
+    # If we have setcap is installed, try setting cap_net_raw+ep,
     # which allows us to install our binaries without the setuid
     # bit.
     if command -v setcap > /dev/null; then
-        if setcap cap_net_raw+ep $PROGRAM; then
-            chmod u-s $PROGRAM
+        if setcap cap_net_raw+ep /bin/ping; then
+            chmod u-s /bin/ping
         else
-            echo "Setcap failed on $PROGRAM, falling back to setuid" >&2
-            chmod u+s $PROGRAM
+            echo "Setcap failed on /bin/ping, falling back to setuid" >&2
+            chmod u+s /bin/ping
         fi
     else
         echo "Setcap is not installed, falling back to setuid" >&2
-        chmod u+s $PROGRAM
+        chmod u+s /bin/ping
     fi
 fi
 
diff --git a/root/var/lib/dpkg/info/libc6:armhf.preinst b/root/var/lib/dpkg/info/libc6:armhf.preinst
--- a/root/var/lib/dpkg/info/libc6:armhf.preinst
+++ b/root/var/lib/dpkg/info/libc6:armhf.preinst
@@ -19,54 +19,81 @@ kfreebsd_compare_versions () {
     test $verA -$2 $verB
 }
 
-if [ "$type" != abort-upgrade -a -z "$DPKG_ROOT" ]
-then
-    # Check if the debconf module is available and usable
-    USE_DEBCONF=
-    if [ "$DEBIAN_HAS_FRONTEND" ]; then
-        # Debconf is already loaded, so we already checked if the frontend
-        # is usable or not
-        USE_DEBCONF=1
-    elif [ -f /usr/share/debconf/confmodule ]; then
-        # cdebconf has a working fallback mechanism in case dialog
-        # is not usable, so do not try to do anything smart here
-        if [ "$DEBCONF_USE_CDEBCONF" ] ; then
-            USE_DEBCONF=1
-        # debconf requires perl
-        elif perl -e "" 2>/dev/null ; then
-            # Check that the selected frontend will work
-            if [ -n "$DEBIAN_FRONTEND" ] ; then
-                frontend="$DEBIAN_FRONTEND"
-            else
-                # Query the frontend without first sourcing the confmodule to avoid
-                # losing control of the tty. This snippet must not be copied blindly.
-                frontend="$(echo 'GET debconf/frontend' | debconf-communicate | sed '/^0 /!d;s/^0 //')"
-                frontend="${frontend:-Dialog}"
-            fi
-            frontend=`echo $frontend | tr '[:upper:]' '[:lower:]'`
-            case "$frontend" in
-            dialog)
-                # debconf uses whiptail by default unless dialog is available and
-                # $DEBCONF_FORCE_DIALOG is set
-                if [ -x "$(which whiptail)" ] && ! ( [ -n "$DEBCONF_FORCE_DIALOG" ] && [ -x "$(which dialog)" ] ); then
-                    frontend=whiptail
-                fi
-                # Only enable debconf if the whiptail/dialog are not available
-                # (in which case debconf has a fallback mechanism) or usable
-                if ! [ -x "$(which $frontend)" ] || $frontend --version > /dev/null 2>&1 ; then
-                    USE_DEBCONF=1
-                fi
-                ;;
-            *)
-                 # For now assume that all other frontends are fine
-                 USE_DEBCONF=1
-                ;;
-            esac
-        fi
-    fi
+# Sanity check.
+# If there are versions of glibc outside of the normal installation
+# location (/lib, /lib64, etc.) then things may break very badly
+# as soon as ld.so is replaced by a new version.  This check is not
+# foolproof, but it's pretty accurate.  This script ignores libraries
+# with different sonames, and libraries incompatible with the 
+# to-be-installed ld.so.
+check_dir () {
+    msg=$1
+    dir=$2
 
-    # Load debconf module if available and usable
-    if [ "$USE_DEBCONF" ]; then
+    # Follow symlinks
+    dir=$(readlink -e $dir || true)
+
+    # Ignore inexistent directories
+    if ! test -d "$dir" ; then
+        return
+    fi
+  
+    # Detect possible candidates
+    files=$(ls $dir | egrep '^(ld|lib(d|c|m|pthread|rt|dl))-2.*.so' 2>/dev/null || true)
+    if test -z "$files" ; then
+        return
+    fi
+  
+    for file in $files ; do
+        lib=$dir/$file
+
+        # Skip if it is a symlink (as installed by lsb-core)
+        if test -L "$lib" ; then
+            continue
+        fi
+
+        # Skip if it is the currently dynamic loader
+        if test "$lib" = "$ldfile" ; then
+            continue
+        fi
+
+        # See if the found libraries are compatible with the system ld.so;
+        # if they aren't, they'll be ignored. Check e_ident, e_type (which
+        # will just be ET_DYN), and e_machine. If a match is found, there
+        # is a risk of breakage.
+        libbytes=`head -c 20 $lib | od -c`
+        if test "$ldbytes" != "$libbytes" ; then 
+          continue
+        fi
+
+        # Binaries owned packages are considered to do the right thing
+        # First try a quick lookup which should catch all cases on a 
+        # normal system
+        if echo $libcfiles | grep -q "[ ^]$lib[ $]" ; then 
+            continue
+        fi
+
+        # Slower lookup to confirm
+        if dpkg-query -S "$lib" >/dev/null 2>&1 ; then
+            continue
+        fi
+
+        # Output an error message and exit
+        echo
+        echo "A copy of the C library was found $msg:"
+        echo "  '$lib'"
+        echo "It is not safe to upgrade the C library in this situation;"
+        echo "please remove that copy of the C library or get it out of"
+        echo "'$dir' and try again."
+        echo
+        exit 1
+    done
+}
+
+if [ "$type" != abort-upgrade ]
+then
+    # Load debconf module if available
+    if [ -f /usr/share/debconf/confmodule ] ; then
         . /usr/share/debconf/confmodule
     fi
 
@@ -116,7 +143,7 @@ then
 
         # sanity checking for the appropriate kernel on each architecture.
         kernel_ver=`uname -r`
-        case ${DPKG_MAINTSCRIPT_ARCH} in
+        case ${DPKG_MAINTSCRIPT_ARCH:-$(dpkg --print-architecture)} in
             *)
                 # The GNU libc requires a >= 3.2 kernel, found in wheezy
                 kernel_ver_min=3.2
@@ -126,7 +153,7 @@ then
 
         if linux_compare_versions "$kernel_ver" lt $kernel_ver_min
         then
-            if [ "$USE_DEBCONF" ]
+            if [ -f /usr/share/debconf/confmodule ]
             then
                 db_version 2.0
                 db_fset glibc/kernel-too-old seen false
@@ -146,7 +173,7 @@ then
 
         if linux_compare_versions "$kernel_ver" lt $kernel_ver_rec
         then
-            if [ "$USE_DEBCONF" ]
+            if [ -f /usr/share/debconf/confmodule ]
             then
                 db_version 2.0
                 db_fset glibc/kernel-not-supported seen false
@@ -169,7 +196,7 @@ then
         kernel_ver_min=8.3
         if kfreebsd_compare_versions "$kernel_ver" lt $kernel_ver_min
         then
-            if [ "$USE_DEBCONF" ]
+            if [ -f /usr/share/debconf/confmodule ]
             then
                 db_version 2.0
                 db_version 2.0
@@ -190,13 +217,61 @@ then
     fi
 fi
 
-if [ "$type" = upgrade -a -z "$DPKG_ROOT" ]
+if [ "$type" = upgrade ]
 then
+    # Try to detect copies of the libc library in the various places
+    # the dynamic linker uses.
+    ldfile=$(readlink -m /lib/ld-linux-armhf.so.3)
+    if test -f "$file"; then
+        ldbytes=$(head -c 20 /lib/ld-linux-armhf.so.3 | od -c)
+    else
+        # If the symlink to the dynamic linker is dangling or missing, set
+        # ldbytes to an empty string, the test below will fail and all the
+        # libraries found will be ignored.
+        ldbytes=""
+    fi
+    libcfiles=$(dpkg-query -L ${DPKG_MAINTSCRIPT_PACKAGE}:${DPKG_MAINTSCRIPT_ARCH} 2>/dev/null)
+
+    dirs="/lib/arm-linux-gnueabihf /lib /lib/tls /lib32 /lib64 /usr/local/lib /usr/local/lib32 /usr/local/lib64"
+    for dir in $dirs ; do
+        check_dir "in an unexpected directory" $dir
+    done
+
+    if test -n "$LD_LIBRARY_PATH"; then
+        dirs=$(echo $LD_LIBRARY_PATH | sed 's/:/ /g')
+        for dir in $dirs ; do
+            check_dir "via LD_LIBRARY_PATH" $dir
+        done
+    fi
+
+    if test -e /etc/ld.so.conf; then
+        dirs=$(echo $(cat /etc/ld.so.conf))
+        if test -n "$dirs" ; then
+            for dir in $dirs ; do
+                check_dir "via /etc/ld.so.conf" $dir
+            done
+        fi
+    fi
+
+    if [ -e /lib/tls/i686/cmov/libc.so.6 ] || [ -e /lib/i686/cmov/libc.so.6 ] ; then
+        status_i686=$(dpkg -s libc6-i686 2>/dev/null | grep ^Status: | sed -e 's/^Status: \(.*\) \(.*\) \(.*\)/\3/g')
+        status_xen=$(dpkg -s libc6-xen 2>/dev/null | grep ^Status: | sed -e 's/^Status: \(.*\) \(.*\) \(.*\)/\3/g')
+        if ([ -z "$status_i686" ] || [ "$status_i686" = "not-installed" ] || [ "$status_i686" = "config-files" ]) && \
+             ([ -z "$status_xen" ] || [ "$status_xen" = "not-installed" ] || [ "$status_xen" = "config-files" ]); then
+            echo
+            echo "A non-dpkg owned copy of the libc6-i686 package was found."
+            echo "It is not safe to upgrade the C library in this situation;"
+            echo "please remove that copy of the C library and try again."
+            echo
+            exit 1
+        fi
+    fi
+
     if [ -n "$preversion" ] && [ -x "$(which ischroot)" ] && ! ischroot; then
 	# NSS authentication trouble guard
-	if dpkg --compare-versions "$preversion" lt 2.31; then
+	if dpkg --compare-versions "$preversion" lt 2.28; then
 	    if pidof xscreensaver xlockmore >/dev/null; then
-		if [ "$USE_DEBCONF" ] ; then
+		if [ -f /usr/share/debconf/confmodule ] ; then
 		    db_version 2.0
 		    db_reset glibc/disable-screensaver
 		    db_input critical glibc/disable-screensaver || true
@@ -225,12 +300,8 @@ then
 	    check="kdm postgresql xdm"
 	    # NSS services check:
 	    	    echo -n "Checking for services that may need to be restarted..."
-	    # Only get the ones that are installed, of the same architecture
-	    # as libc (or arch all) and configured. Restart openssh-server even
-	    # if only half-configured to continue accepting new connections
-	    # during the upgrade.
-	    check=$(dpkg-query -W -f='${binary:Package} ${Status} ${Architecture}\n' $check 2> /dev/null | \
-			grep -E "(^openssh-server .* unpacked|installed) (all|${DPKG_MAINTSCRIPT_ARCH})$" | sed 's/[: ].*//')
+	    # Only get the ones that are installed, and configured
+	    check=$(dpkg -s $check 2> /dev/null | egrep '^Package:|^Status:' | awk '{if ($1 ~ /^Package:/) { package=$2 } else if ($0 ~ /^Status: .* installed$/) { print package }}')
 	    # some init scripts don't match the package names
 	    check=$(echo $check | \
 		    sed -e's/\bapache2.2-common\b/apache2/g' \
@@ -240,7 +311,6 @@ then
 			-e's/\blpr\b/lpd/g' \
 			-e's/\blpr-ppd\b/lpd-ppd/g' \
 			-e's/\bmysql-server\b/mysql/g' \
-			-e's/\bopenssh-server\b/ssh/g' \
 			-e's/\bsasl2-bin\b/saslauthd/g' \
 			-e's/\bsamba\b/smbd/g' \
 			-e's/\bpostgresql-common\b/postgresql/g' \
@@ -257,7 +327,7 @@ then
 	    done
 
 	    if [ -n "$services" ]; then 
-		if [ "$USE_DEBCONF" ] ; then
+		if [ -f /usr/share/debconf/confmodule ] ; then
 	            db_version 2.0
 		    db_reset glibc/upgrade
 		    db_subst glibc/upgrade services $services
@@ -304,7 +374,7 @@ then
 	            exit 1
 		fi
 	    fi
-	fi # end upgrading and $preversion lt 2.31
+	fi # end upgrading and $preversion lt 2.28
     fi # Upgrading
 
     # This will keep us from using hwcap libs (optimized) during an
@@ -315,12 +385,12 @@ fi
 
 
 if [ -n "$preversion" ]; then
-    if dpkg --compare-versions "$preversion" lt 2.31; then
+    if dpkg --compare-versions "$preversion" lt 2.28; then
        # unconditionally wipe ld.so.cache on major version upgrades; this
        # makes those upgrades a bit slower, but is less error-prone than
        # hoping we notice every time the cache format is changed upstream
-       rm -f "$DPKG_ROOT/etc/ld.so.cache"
-       rm -f "$DPKG_ROOT/var/cache/ldconfig/aux-cache"
+       rm -f /etc/ld.so.cache
+       rm -f /var/cache/ldconfig/aux-cache
     fi
 fi
 
diff --git a/root/var/lib/dpkg/info/man-db.postinst b/root/var/lib/dpkg/info/man-db.postinst
--- a/root/var/lib/dpkg/info/man-db.postinst
+++ b/root/var/lib/dpkg/info/man-db.postinst
@@ -99,7 +99,7 @@ else
     run_mandb "Updating database of manual pages ..." -pq
 fi
 
-# Automatically added by dh_apparmor/2.13.6-9
+# Automatically added by dh_apparmor/2.13.2-7
 if [ "$1" = "configure" ]; then
     APP_PROFILE="/etc/apparmor.d/usr.bin.man"
     if [ -f "$APP_PROFILE" ]; then
@@ -118,16 +118,7 @@ if [ "$1" = "configure" ]; then
     fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.3.3
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
-	# In case this system is running systemd, we need to ensure that all
-	# necessary tmpfiles (if any) are created before starting.
-	if [ -d /run/systemd/system ] ; then
-		systemd-tmpfiles --create man-db.conf >/dev/null || true
-	fi
-fi
-# End automatically added section
-# Automatically added by dh_installsystemd/13.3.3
+# Automatically added by dh_systemd_enable/12
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'man-db.timer' >/dev/null || true
@@ -144,16 +135,20 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installsystemd/13.3.3
+# Automatically added by dh_installinit/12
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# In case this system is running systemd, we need to ensure that all
+	# necessary tmpfiles (if any) are created before starting.
+	if [ -d /run/systemd/system ] ; then
+		systemd-tmpfiles --create man-db.conf >/dev/null || true
+	fi
+fi
+# End automatically added section
+# Automatically added by dh_systemd_start/12
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
-		if [ -n "$2" ]; then
-			_dh_action=restart
-		else
-			_dh_action=start
-		fi
-		deb-systemd-invoke $_dh_action 'man-db.service' 'man-db.timer' >/dev/null || true
+		deb-systemd-invoke start 'man-db.service' 'man-db.timer' >/dev/null || true
 	fi
 fi
 # End automatically added section
diff --git a/root/var/lib/dpkg/info/raspberrypi-sys-mods.postinst b/root/var/lib/dpkg/info/raspberrypi-sys-mods.postinst
--- a/root/var/lib/dpkg/info/raspberrypi-sys-mods.postinst
+++ b/root/var/lib/dpkg/info/raspberrypi-sys-mods.postinst
@@ -1,40 +1,82 @@
 #!/bin/sh -e
 
-remove_ms_stubs () {
+check_audio () {
+  # audio dtparam mentioned in config.txt (enabled, disabled or commented out)
+  AM_PAT="^[[:space:]]*#?[[:space:]]*(device_tree_param|dtparam)[[:space:]]*=[[:space:]]*([^,]*,)*audio[[:space:]]*=.*$"
+  # snd_bcm2835 module enabled pattern
+  SND_PAT="^[[:space:]]*snd(_|-)bcm2835[[:space:]]*$"
+
+  if grep -q -E "$AM_PAT" /boot/config.txt; then
+    return 0;
+  fi
+
+  if grep -q -E "^[[:space:]]*\[.*\]" /boot/config.txt; then
+    return 0;
+  fi
+
+  if grep -q -E "$SND_PAT" /etc/modules; then
+    echo "Enabling audio in config.txt and removing from /etc/modules..."
+    printf '\n# Enable audio (added by raspberrypi-sys-mods)\n' >> /boot/config.txt
+    echo "dtparam=audio=on" >> /boot/config.txt
+    MODBAK=/etc/modules.ui-mods.bak
+    grep -v -E "$SND_PAT" /etc/modules > ${MODBAK}
+    mv ${MODBAK} /etc/modules
+  else
+    echo "Disabling audio in config.txt..."
+    printf '\n# Disable audio (added by raspberrypi-sys-mods)\n' >> /boot/config.txt
+    echo "dtparam=audio=no" >> /boot/config.txt
+  fi
+}
+
+block_ms_repo () {
   eval "$(apt-config shell APT_SOURCE_PARTS Dir::Etc::sourceparts/d)"
   CODE_SOURCE_PART="${APT_SOURCE_PARTS}vscode.list"
   eval "$(apt-config shell APT_TRUSTED_PARTS Dir::Etc::trustedparts/d)"
   CODE_TRUSTED_PART="${APT_TRUSTED_PARTS}microsoft.gpg"
-  grep -qsv '^[[:space:]]*#' "$CODE_SOURCE_PART" || rm -f "$CODE_SOURCE_PART" ||:
-  grep -qsv '^[[:space:]]*#' "$CODE_TRUSTED_PART" || rm -f "$CODE_TRUSTED_PART" ||:
+  echo "### Disabled by raspberrypi-sys-mods ###" > "$CODE_TRUSTED_PART" > "$CODE_SOURCE_PART" ||:
 }
 
 case "${1}" in
   configure)
-    if dpkg --compare-versions "${2}" lt-nl "20210928"; then
-      if [ -f /etc/systemd/system/dhcpcd.service.d/wait.conf ]; then
-        echo "Fixing previous dhcpcd path in wait.conf drop-in..."
-        sed -i 's|lib/dhcpcd5|sbin|' /etc/systemd/system/dhcpcd.service.d/wait.conf
-      fi
-      if [ "$(readlink -f /etc/systemd/network/99-default.link)" = "/dev/null" ]; then
-        echo "Fixing predictable interface names..."
-        ln -sf /dev/null /etc/systemd/network/73-usb-net-by-mac.link
-      fi
+    if dpkg --compare-versions "${2}" lt "20160112"; then
+      check_audio
     fi
-    if dpkg --compare-versions "${2}" lt-nl "20220110+1"; then
-      if [ -f /etc/systemd/system/dhcpcd.service.d/wait.conf ]; then
-        echo "Fixing previous dhcpcd wait.conf drop-in to prevent double logging..."
-        sed -i 's|dhcpcd -w$|dhcpcd -w -q|' /etc/systemd/system/dhcpcd.service.d/wait.conf
-      fi
+    if dpkg --compare-versions "${2}" lt "20160321+1"; then
+      echo "Fixing file capabilities..."
+      setcap cap_dac_override,cap_sys_ptrace+ep /usr/bin/systemd-detect-virt || true
     fi
-    if dpkg --compare-versions "${2}" lt-nl "20220106"; then
-      echo "Removing vscode repo stubs..."
-      remove_ms_stubs
+    if dpkg --compare-versions "${2}" lt "20160321"; then
+      echo "Adjusting cmdline.txt..."
+      sed -e "s|=ttyAMA0|=serial0|;s|=ttyS0|=serial1|;" -i /boot/cmdline.txt || echo "Failed"
     fi
-    if dpkg --compare-versions "${2}" lt-nl "20220224" && \
-        [ "$(dpkg --print-architecture | grep -o '^.\{3\}')" = "arm" ]; then
-      echo "Adding 'flush' option to boot partition..."
-      sed -i 's/^\(.* \/boot .*defaults\) \{6\}\(.*\)$/\1,flush\2/' /etc/fstab
+    if dpkg --compare-versions "${2}" lt "20160916"; then
+      echo "Removing old sysctl tweaks, if present..."
+      sed -n '1h;1!H;${;g;s/\n\# rpi tweaks\nvm\.swappiness=1\nvm\.min_free_kbytes = 8192//g;p;}' -i /etc/sysctl.conf
+    fi
+    if dpkg --compare-versions "${2}" lt-nl "20161018" && \
+       ! grep -Eq '^pi ALL=\(ALL\) NOPASSWD: ALL$' /etc/sudoers; then
+      echo "Old entry not found. Disabling new NOPASSWD line..."
+      sed -e '/^pi/ s/^#*/#/' -i /etc/sudoers.d/010_pi-nopasswd || echo "Failed"
+    fi
+    if dpkg --compare-versions "${2}" lt "20161018+3"; then
+      echo "Removing old NOPASSWD line, if present..."
+      sed '/pi ALL=(ALL) NOPASSWD: ALL/d' -i /etc/sudoers || echo "Failed"
+    fi
+    if dpkg --compare-versions "${2}" lt "20170313"; then
+      echo "Updating documentation URL in /boot/config.txt..."
+      sed -i 's|http://www.raspberrypi.org/documentation/configuration/config-txt.md|http://rpf.io/configtxtreadme|' /boot/config.txt || echo "Failed"
+    fi
+    if dpkg --compare-versions "${2}" lt "20170717"; then
+      deb-systemd-invoke disable apply_noobs_os_config.service
+      deb-systemd-invoke disable regenerate_ssh_host_keys.service
+    fi
+    if dpkg --compare-versions "${2}" lt "20180328+1"; then
+      echo "Updating apt sources from {mirrordirector,archive}.raspbian.org to raspbian.raspberrypi.org..."
+      find /etc/apt/sources.list* -type f -exec sed -i -E 's/(mirrordirector|archive)\.raspbian\.org/raspbian.raspberrypi.org/g' {} \;
+    fi
+    if dpkg --compare-versions "${2}" lt "20210310"; then
+      echo "Blocking vscode repo..."
+      block_ms_repo
     fi
     ;;
 
@@ -48,7 +90,7 @@ case "${1}" in
     ;;
 esac
 
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'rpi-display-backlight.service' >/dev/null || true
@@ -65,7 +107,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'rpi-display-backlight.service' >/dev/null || true
@@ -82,7 +124,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'sshswitch.service' >/dev/null || true
@@ -99,7 +141,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'apply_noobs_os_config.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -116,7 +158,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'apply_noobs_os_config.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'rpi-display-backlight.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -133,7 +175,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'rpi-display-backlight.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'sshswitch.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -150,7 +192,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'sshswitch.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'apply_noobs_os_config.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -167,7 +209,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'apply_noobs_os_config.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'regenerate_ssh_host_keys.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -184,7 +226,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'regenerate_ssh_host_keys.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'rpi-display-backlight.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -201,7 +243,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'rpi-display-backlight.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if deb-systemd-helper debian-installed 'sshswitch.service'; then
 		# This will only remove masks created by d-s-h on package removal.
@@ -218,7 +260,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	deb-systemd-helper update-state 'sshswitch.service' >/dev/null || true
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'apply_noobs_os_config.service' >/dev/null || true
@@ -235,7 +277,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'regenerate_ssh_host_keys.service' >/dev/null || true
@@ -252,7 +294,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'rpi-display-backlight.service' >/dev/null || true
@@ -269,7 +311,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_enable/13.3.4
+# Automatically added by dh_systemd_enable/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# This will only remove masks created by d-s-h on package removal.
 	deb-systemd-helper unmask 'sshswitch.service' >/dev/null || true
@@ -286,7 +328,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_start/13.3.4
+# Automatically added by dh_systemd_start/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -296,7 +338,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_start/13.3.4
+# Automatically added by dh_systemd_start/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -306,7 +348,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_start/13.3.4
+# Automatically added by dh_systemd_start/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -316,7 +358,7 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_systemd_start/13.3.4
+# Automatically added by dh_systemd_start/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -d /run/systemd/system ]; then
 		systemctl --system daemon-reload >/dev/null || true
@@ -326,21 +368,20 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installdeb/13.3.4
+# Automatically added by dh_installdeb/13.2~bpo10+1
 dpkg-maintscript-helper rm_conffile /etc/profile.d/sshpasswd.sh 20161220 -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/profile.d/wifi-country.sh 20190429 -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/modprobe.d/blacklist-rtl8192cu.conf 20190730 -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/apt/preferences.d/3rd_parties.pref 20210310 -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/modules-load.d/aes-neon.conf 20220224 -- "$@"
 # End automatically added section
-# Automatically added by dh_installinit/13.3.4
+# Automatically added by dh_installinit/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/rpi-display-backlight" ]; then
 		update-rc.d rpi-display-backlight defaults >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit/13.3.4
+# Automatically added by dh_installinit/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/sshswitch" ]; then
 		update-rc.d sshswitch defaults >/dev/null
@@ -353,14 +394,14 @@ if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-decon
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit/13.3.4
+# Automatically added by dh_installinit/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/apply_noobs_os_config" ]; then
 		update-rc.d apply_noobs_os_config defaults >/dev/null || exit 1
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installinit/13.3.4
+# Automatically added by dh_installinit/13.2~bpo10+1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	if [ -x "/etc/init.d/regenerate_ssh_host_keys" ]; then
 		update-rc.d regenerate_ssh_host_keys defaults >/dev/null || exit 1
diff --git a/root/var/lib/dpkg/info/systemd.postinst b/root/var/lib/dpkg/info/systemd.postinst
--- a/root/var/lib/dpkg/info/systemd.postinst
+++ b/root/var/lib/dpkg/info/systemd.postinst
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /bin/sh
 
 set -e
 
@@ -12,9 +12,19 @@ _update_catalog() {
     journalctl --update-catalog || true
 }
 
-# Update Message Catalogs database in response to dpkg trigger
+# Update Message Catalogs database and reload in response to dpkg triggers
 if [ "$1" = "triggered" ]; then
-    _update_catalog
+    shift
+    for trigger in "$@"; do
+        case $trigger in
+            /usr/lib/systemd/catalog)
+                _update_catalog
+                ;;
+            /etc/init.d)
+                _systemctl daemon-reload || true
+                ;;
+        esac
+    done
     exit 0
 fi
 
@@ -24,9 +34,14 @@ if [ -z "$2" ]; then
     systemctl enable remote-fs.target || true
 fi
 
-# Enable systemd-pstore by default on new installs and upgrades, see #952767
-if dpkg --compare-versions "$2" lt "245.4-4~"; then
-    systemctl enable systemd-pstore.service || true
+# Enable timesyncd by default on new installs installs and upgrades
+if dpkg --compare-versions "$2" lt "218-11~"; then
+    systemctl enable systemd-timesyncd.service || true
+fi
+
+# Enable ondemand by default on new installs installs and upgrades
+if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" lt "231-7~"; then
+    systemctl enable ondemand.service || true
 fi
 
 # Do a one-time migration of the local time setting
@@ -81,21 +96,29 @@ systemd-machine-id-setup
 # Setup system users and groups
 addgroup --quiet --system systemd-journal
 
+# We need to stop running services before we call adduser
+RESTART=""
+if dpkg --compare-versions "$2" lt-nl "239-6"; then
+    for s in systemd-networkd systemd-timesyncd systemd-resolved ; do
+        if _systemctl -q is-active $s; then
+            _systemctl stop $s
+            RESTART="$s $RESTART"
+        fi
+    done
+fi
+
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Time Synchronization" systemd-timesync
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Network Management" systemd-network
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Resolver" systemd-resolve
 
-# Enable persistent journal, in auto-mode, by default on new installs and upgrades
-if dpkg --compare-versions "$2" lt "244.1-2~"; then
-    mkdir -p /var/log/journal
-    # Applying ACLs requires a mounted /proc and systemd-tmpfiles will fail if
-    # /proc is not available. Skip systemd-tmpfiles in this case. This should
-    # be fine, as this typically means we are inside a chroot and systemd is
-    # not currently active. The permissions will be applied on the next boot.
-    # https://github.com/systemd/systemd/issues/14745
-    if mountpoint -q /proc; then
-        systemd-tmpfiles --create --prefix /var/log/journal
+# Remove old state directory of systemd-timesyncd
+if dpkg --compare-versions "$2" lt-nl "240-3~"; then
+    if [ -L /var/lib/systemd/timesync ] ; then
+        rm /var/lib/systemd/timesync
+        rm -rf /var/lib/private/systemd/timesync
     fi
 fi
 
@@ -106,13 +129,26 @@ if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
     # don't restart logind; this can be done again once this gets implemented:
     # https://github.com/systemd/systemd/issues/1163
-    if dpkg --compare-versions "$2" lt-nl "246.2-2~"; then
-        # the socket configuration changed
-        _systemctl stop systemd-networkd.socket || true
-    fi
     _systemctl try-restart systemd-networkd.service || true
     _systemctl try-restart systemd-resolved.service || true
+    _systemctl try-restart systemd-timesyncd.service || true
     _systemctl try-restart systemd-journald.service || true
+fi
+
+# Restart services which we stopped earlier
+# This needs to run after daemon-rexec
+if dpkg --compare-versions "$2" lt-nl "239-6"; then
+    for s in $RESTART ; do
+        _systemctl start $s
+    done
+fi
+
+# Cleanup hwclock-save.service, which was shipped in jessie.
+if dpkg --compare-versions "$2" lt-nl "228-5~"; then
+   for t in reboot halt poweroff ; do
+       rm -f /etc/systemd/system/${t}.target.wants/hwclock-save.service
+       rmdir --ignore-fail-on-non-empty /etc/systemd/system/${t}.target.wants 2> /dev/null || true
+   done
 fi
 
 if dpkg --compare-versions "$2" lt-nl "235-3~"; then
@@ -134,27 +170,18 @@ if dpkg --compare-versions "$2" lt-nl "239-12~"; then
     fi
 fi
 
-if dpkg --compare-versions "$2" lt-nl "245.4-4~"; then
-    # systemd-pstore.service is now enabled via sysinit.target
-    rm -f /etc/systemd/system/systemd-remount-fs.service.wants/systemd-pstore.service
-    rmdir --ignore-fail-on-non-empty /etc/systemd/system/systemd-remount-fs.service.wants 2> /dev/null || true
-fi
-
-if dpkg --compare-versions "$2" lt-nl "245.4-5~"; then
-    # Clean up removed ondemand service
-    rm -f /etc/systemd/system/multi-user.target.wants/ondemand.service
-fi
-
-# Automatically added by dh_installtmpfiles/13.3.4
+# Automatically added by dh_installinit/12.1.1
 if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
 	# In case this system is running systemd, we need to ensure that all
 	# necessary tmpfiles (if any) are created before starting.
 	if [ -d /run/systemd/system ] ; then
-		systemd-tmpfiles --create debian.conf home.conf journal-nocow.conf legacy.conf systemd-nologin.conf systemd-pstore.conf systemd-tmp.conf systemd.conf tmp.conf var.conf x11.conf >/dev/null || true
+		systemd-tmpfiles --create debian.conf home.conf journal-nocow.conf legacy.conf systemd-nologin.conf systemd.conf tmp.conf var.conf x11.conf >/dev/null || true
 	fi
 fi
 # End automatically added section
-# Automatically added by dh_installdeb/13.3.4
+# Automatically added by dh_installdeb/12.1.1
+dpkg-maintscript-helper rm_conffile /etc/X11/xinit/xinitrc.d/50-systemd-user.sh 228-3\~ -- "$@"
+dpkg-maintscript-helper rm_conffile /etc/systemd/bootchart.conf 230-1\~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.hostname1.conf 233-3\~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.locale1.conf 233-3\~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.login1.conf 233-3\~ -- "$@"
@@ -164,8 +191,5 @@ dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.resolve
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.systemd1.conf 233-3\~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.timedate1.conf 233-3\~ -- "$@"
 dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.systemd-shim.conf 239-15\~ systemd-shim -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/dhcp/dhclient-exit-hooks.d/timesyncd 245.4-2\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/systemd/timesyncd.conf 245.4-2\~ -- "$@"
-dpkg-maintscript-helper rm_conffile /etc/pam.d/systemd-user 247\~rc2-3\~ -- "$@"
 # End automatically added section
 
